# Comment: This file stores the machine configuration
---
MachineConfig: THzSTM
Channels:
  LI_Demod_1_X:
      nickname: dIdV
      scaling: 1.e12
      unit: pS
  LI_Demod_1_Y:
      nickname: dIdV_Y
      scaling: 1e12
      unit: pS
  Z:
      nickname: z
      scaling: 1e9
      unit: nm
  Current:
      nickname: I
      scaling: 1.0e12
      unit: pA
  Bias:
      nickname: V
      scaling: 1
      unit: V
  Frequency_Shift:
      nickname: df
      scaling: 1
      unit: Hz
  Amplitude:
      nickname: A
      scaling: 1e9
      unit: nm
  Excitation:
      nickname: exc
      scaling: 1
      unit: V
  Temperature_1:
      nickname: T1
      scaling: 1
      unit: K
  Temperature 1 (V):
      nickname: T1_V
      scaling: 1
      unit: V
  Bias (V):
      nickname: V
      scaling: 1
      unit: V
  Bias calc (V):
      nickname: V
      scaling: 1
      unit: V
  Bias [bwd] (V):
      nickname: V_bw
      scaling: 1
      unit: V
  Current (A):
      nickname: I
      scaling: 1e12
      unit: pA
  Current [bwd] (A):
      nickname: I_bw
      scaling: 1e12
      unit: pA
  Amplitude (m):
      nickname: A
      scaling: 1e9
      unit: nm
  Amplitude [bwd] (m):
      nickname: A_bw
      scaling: 1e9
      unit: nm
  Excitation (V):
      nickname: exc
      scaling: 1
      unit: V
  Excitation [bwd] (V):
      nickname: exc_bw
      scaling: 1
      unit: V
  Frequency Shift (Hz):
      nickname: df
      scaling: 1
      unit: Hz
  Frequency Shift [bwd] (Hz):
      nickname: df_bw
      scaling: 1
      unit: Hz
  LI Demod 1 X (A):
      nickname: dIdV
      scaling: 1e12
      unit: pS
  LI Demod 1 X (A) [bwd]:
      nickname: dIdV_bw
      scaling: 1e12
      unit: pS
  PMT (V):
      nickname: PMT
      scaling: 1
      unit: V
  Counter 1 (Hz):
      nickname: counter
      scaling: 1
      unit: Hz
  Counter_1:
      nickname: counter
      scaling: 1
      unit: Hz
  Z rel (m):
      nickname: zrel
      scaling: 1e9
      unit: nm
  Z (m):
      nickname: zspec
      scaling: 1e9
      unit: nm
  Time (s):
      nickname: t
      scaling: 1
      unit: s
  LI Demod 0 X (V):
      nickname: EOS
      scaling: 1
      unit: V
  LI Demod 0 Y (V):
      nickname: EOS_Y
      scaling: 1
      unit: V
  LI Demod 3 X (A):
      nickname: I_THz
      scaling: 1e12
      unit: pA
  LI Demod 3 Y (A):
      nickname: I_THz_Y
      scaling: 1e12
      unit: pA
  LI_Demod_3_X:
      nickname: I_THz
      scaling: 1e12
      unit: pA
  LI_Demod_3_Y:
      nickname: I_THz_Y
      scaling: 1e12
      unit: pA
  Delay Sampling (s):
      nickname: Delay
      scaling: 1
      unit: ps
  Delay THz1 (s):
      nickname: Delay1
      scaling: 1
      unit: ps
  Delay THz2 (s):
      nickname: Delay2
      scaling: 1
      unit: ps
  Position Phase1 (m):
      nickname: Phase
      scaling: 1e3
      unit: mm
  Rotation1 (deg):
      nickname: Rot1
      scaling: 1
      unit: deg
  Rotation2 (deg):
      nickname: Rot2
      scaling: 1
      unit: deg
  Rotation (deg):
      nickname: Rot
      scaling: 1
      unit: deg
  Index:
      nickname: Index
      scaling: 1
      unit: N
  Wavelength:
      nickname: Wavelength
      scaling: 1
      unit: nm
  Intensity:
      nickname: Intensity
      scaling: 1
      unit: 'Counts'
  LI Demod 0 X (V):
      nickname: EOS
      scaling: 1
      unit: V
  LI Demod 0 Y (V):
      nickname: EOS_Y
      scaling: 1
      unit: V
  LI Demod 3 X (A):
      nickname: I_THz
      scaling: 1e12
      unit: pA
  LI Demod 3 Y (A):
      nickname: I_THz_Y
      scaling: 1e12
      unit: pA
  LI_Demod_3_X:
      nickname: I_THz
      scaling: 1e12
      unit: pA
  LI_Demod_3_Y:
      nickname: I_THz_Y
      scaling: 1e12
      unit: pA
  Delay Sampling (s):
      nickname: Delay
      scaling: 1
      unit: ps
  Delay THz1 (s):
      nickname: Delay1
      scaling: 1
      unit: ps
  Delay THz2 (s):
      nickname: Delay2
      scaling: 1
      unit: ps
  Position Phase1 (m):
      nickname: Phase
      scaling: 1e3
      unit: mm
  Rotation1 (deg):
      nickname: Rot1
      scaling: 1
      unit: deg
  Rotation2 (deg):
      nickname: Rot2
      scaling: 1
      unit: deg
  Rotation (deg):
      nickname: Rot
      scaling: 1
      unit: deg
  Index:
      nickname: Index
      scaling: 1
      unit: N
  Wavelength:
      nickname: Wavelength
      scaling: 1
      unit: nm
  Intensity:
      nickname: Intensity
      scaling: 1
      unit: 'count'

Parameters:
  X (m):
      nickname: x
      scaling: 1.e9
      unit: nm
  Y (m):
      nickname: y
      scaling: 1e9
      unit: nm
  Z (m):
      nickname: z
      scaling: 1e9
      unit: nm
  bias:
      nickname: V
      scaling: 1
      unit: V
  z-controller>setpoint:
      nickname: setpoint
      scaling: 1e12
      unit: pA
  scan_angle:
      nickname: angle
      scaling: 1
      unit: deg
  Comments:
      nickname: comment
      scaling: null
      unit: null
  Comment01:
      nickname: comment_spec
      scaling: null
      unit: null
  Lock-in>Amplitude:
      nickname: lockin_amplitude
      scaling: 1e3
      unit: mV
  Lock-in>Reference phase D1 (deg):
      nickname: lockin_phase
      scaling: 1
      unit: deg
  Lock-in>Frequency (Hz):
      nickname: lockin_frequency
      scaling: 1
      unit: Hz
  Temperature 2>Temperature 2 (K):
      nickname: temperature
      scaling: 1
      unit: K
  Current>Current (A):
      nickname: setpoint_spec
      scaling: 1e12
      unit: pA
  Bias>Bias (V):
      nickname: V_spec
      scaling: 1
      unit: V
  z-controller>tiplift (m):
      nickname: z_offset
      scaling: 1e9
      unit: nm
  Parameter>Delay Sampling (s):
      nickname: Sampling
      scaling: 1e12
      unit: ps
  Parameter>Delay PP1 (s):
      nickname: PP1
      scaling: 1e12
      unit: ps
  Parameter>Delay PP2 (s):
      nickname: PP2
      scaling: 1e12
      unit: ps
  Parameter>Angle Rot1 (deg):
      nickname: Rot1
      scaling: 1
      unit: deg
  Parameter>Angle Rot2 (deg):
      nickname: Rot2
      scaling: 1
      unit: deg
  Parameter>Position Phase1 (m):
      nickname: Phase
      scaling: 1e3
      unit: mm
  Parameter>Position_Phase1 (m):
      nickname: Phase_depricated
      scaling: 1e3
      unit: mm
  Ext. VI 1>Laser>PP Frequency (MHz):
      nickname: frep
      scaling: 1
      unit: MHz
